language: python
python:
  - "3.8"
cache: pip
install:
  - pip install numpy pandas furl marshmallow pyotp requests
  - pip install coverage
script:
  - coverage run -m tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
